In [48]:
from dbase import *
from imports_func import *

In [49]:
X=np.load('/home/miquel/ForMiquel/CLEAN2/X_c1_1j.npy') 
#X2=np.load('/home/miquel/ForMiquel/CLEAN2/X_c2_1j.npy')
#X3=np.load('/home/miquel/ForMiquel/CLEAN2/X_c3_1j.npy')
#X=np.concatenate((X1, X2), axis=1)
#X=np.concatenate((X, X3), axis=1)
y=np.load('/home/miquel/ForMiquel/CLEAN2/y_short.npy') #subject labels
sub_id=np.load('/home/miquel/ForMiquel/CLEAN2/sub_id_short.npy') #subject idxs
jac_idx=np.load('/home/miquel/ForMiquel/CLEAN2/jac_idx_1j.npy')

In [50]:
# build vector with dt's
dt=[]
for i in range(0,len(sub_id)):
    dt.append(Subjects[sub_id[i]].jacobians[jac_idx[i]].dt)
dt = np.asarray(dt)    

In [46]:
spl = StratifiedShuffleSplit(n_splits=1, test_size=0.3, random_state=36)
for train_index, test_index in spl.split(X, y): #split in subjects
    X_train = X[train_index,:]
    X_test = X[test_index,:]
    y_train = y[train_index]
    y_test = y[test_index]
    dt_test = dt[test_index]

In [51]:
print(np.shape(X_train))
S = SelectPercentile(percentile=5.5)
#S = SelectKBest(f_classif, k=1000)
S.fit(X_train, y_train)
X_train = X_train[:,S.get_support()]
X_test = X_test[:,S.get_support()]

print(np.shape(X_train))
print(np.shape(X_test))

    
#clf = SVC(kernel="linear", C=100000)
clf = LogisticRegression(solver='liblinear', penalty='l2', C=10000)

y_score = clf.fit(X_train, y_train).decision_function(X_test)
pred = clf.predict(X_test)

mask0 = np.where(dt_test<=400)
mask1 = np.where(dt_test>400)
mask0 = np.asarray(mask0)
mask1 = np.asarray(mask1)

pred_0 = pred[mask0][0]
y_test_0 = y_test[mask0][0]
y_score_0 = y_score[mask0][0]
pred_1 = pred[mask1][0]
y_test_1 = y_test[mask1][0]
y_score_1 = y_score[mask1][0]

acc_0 = accuracy_score(y_test_0, pred_0)
roc_0 = roc_auc_score(y_test_0, y_score_0)
f1_0 = f1_score(y_test_0, pred_0)
mcc_0 = matthews_corrcoef(y_test_0, pred_0)
aps_0 = average_precision_score(y_test_0, y_score_0)

print('metrics for jacobians 0y')
print(acc_0)
print(roc_0)
print(f1_0)
print(mcc_0)
print(aps_0)
print(confusion_matrix(y_test_0, pred_0))

acc_1 = accuracy_score(y_test_1, pred_1)
roc_1=roc_auc_score(y_test_1, y_score_1)
f1_1=f1_score(y_test_1, pred_1)
mcc_1=matthews_corrcoef(y_test_1, pred_1)
aps_1=average_precision_score(y_test_1, y_score_1)

print('metrics for jacobians 1y')
print(acc_1)
print(roc_1)
print(f1_1)
print(mcc_1)
print(aps_1)
print(confusion_matrix(y_test_1, pred_1))

(86, 31118)
(86, 1712)
(38, 1712)
metrics for jacobians 0y
0.733333333333
0.857142857143
0.6
0.534522483825
0.84410430839
[[8 0]
 [4 3]]
metrics for jacobians 1y
0.565217391304
0.491666666667
0.375
0.0416666666667
0.579014123132
[[10  5]
 [ 5  3]]


pred_0

array([[ -1,  -2,  -6,  -7,  -8,  -9, -10, -11, -12, -15, -17, -20, -21,
        -22, -23, -26, -27, -28, -30, -33, -35]])