In [2]:
from dbase import *

In [17]:
ADRIA = open('/home/miquel/ForMiquel/CLEAN/jacobian_list_txt.txt', 'r')

X=np.zeros((4))

for line in ADRIA:
    array = line.split(",")
    array[len(array)-1] = array[len(array)-1].replace("\n","")
    X = np.vstack((X, array))
X=X[1:,:]    
print(X)

[['3' '0' '1' '4']
 ['5' '0' '1' '2']
 ['10' '0' '1' '4']
 ..., 
 ['4898' '0' '1' '4']
 ['4925' '0' '1' '4']
 ['4947' '0' '1' '4']]


In [57]:
X2=np.zeros((4))
for s in Subjects:
    rid = s.rid
    for j in s.jacobians:
        step_reference = j.reference.step
        step_target = j.target.step
        label = j.label - 1
        
        if label != -1:
            array = [rid, step_reference, step_target, label]
            X2 = np.vstack((X2, array))
            
X2 = X2[1:,:] 
#X2 = np.sort(X2, axis=0)
print(X2)
        

[[  2.95000000e+02   0.00000000e+00   1.00000000e+00   2.00000000e+00]
 [  2.95000000e+02   0.00000000e+00   2.00000000e+00   2.00000000e+00]
 [  2.95000000e+02   0.00000000e+00   3.00000000e+00   2.00000000e+00]
 ..., 
 [  4.29200000e+03   0.00000000e+00   1.00000000e+00   1.00000000e+00]
 [  4.36500000e+03   0.00000000e+00   1.00000000e+00   2.00000000e+00]
 [  4.76400000e+03   0.00000000e+00   1.00000000e+00   4.00000000e+00]]


In [20]:
print(len(X))
print(len(X2))


957
727


In [42]:
y=list(np.transpose(X[:,3]))
print('list Adrià labels: class1:', y.count('0'),'class2:',y.count('1'),'class3:',y.count('2'),'class4:',y.count('3'),'class5:', y.count('4'))
y=list(np.transpose(X2[:,3]))
print('list Miquel labels: class1:', y.count(0),'class2:',y.count(1),'class3:',y.count(2),'class4:',y.count(3),'class5:', y.count(4))


list Adrià labels: class1: 203 class2: 35 class3: 136 class4: 34 class5: 549
list Miquel labels: class1: 216 class2: 32 class3: 137 class4: 17 class5: 325


In [126]:
for line in X:
    if line[0] == '618':
        print(line)

['618' '0' '1' '0']
['618' '0' '2' '1']
['618' '0' '3' '1']
['618' '1' '2' '1']
['618' '1' '3' '1']
['618' '2' '3' '2']


In [127]:
for line in X2:
    if line[0] == 618:
        print(line)

[ 618.    0.    1.    0.]
[ 618.    0.    2.    1.]
[ 618.    0.    3.    1.]
[ 618.    0.    4.    0.]
[ 618.    0.    5.    0.]
[ 618.    1.    2.    1.]
[ 618.    1.    3.    1.]
[ 618.    1.    4.    0.]
[ 618.    1.    5.    0.]
[ 618.    2.    3.    2.]
[ 618.    4.    5.    0.]


In [102]:
for line in X2:
    if line[3] == 0:
        print(line)

[ 413.    0.    1.    0.]
[ 559.    0.    1.    0.]
[ 559.    0.    2.    0.]
[ 559.    0.    3.    0.]
[ 559.    1.    2.    0.]
[ 559.    1.    3.    0.]
[ 559.    2.    3.    0.]
[ 685.    0.    1.    0.]
[ 685.    0.    2.    0.]
[ 685.    0.    3.    0.]
[ 685.    0.    4.    0.]
[ 685.    1.    2.    0.]
[ 685.    1.    3.    0.]
[ 685.    1.    4.    0.]
[ 685.    2.    3.    0.]
[ 685.    2.    4.    0.]
[ 685.    3.    4.    0.]
[  4.21300000e+03   0.00000000e+00   1.00000000e+00   0.00000000e+00]
[ 602.    0.    1.    0.]
[ 610.    0.    1.    0.]
[ 610.    0.    2.    0.]
[ 610.    0.    3.    0.]
[ 610.    1.    2.    0.]
[ 610.    1.    3.    0.]
[ 610.    2.    3.    0.]
[ 498.    0.    1.    0.]
[ 498.    0.    2.    0.]
[ 498.    1.    2.    0.]
[ 70.   0.   1.   0.]
[  1.20600000e+03   0.00000000e+00   1.00000000e+00   0.00000000e+00]
[ 1206.     0.     2.     0.]
[  1.20600000e+03   1.00000000e+00   2.00000000e+00   0.00000000e+00]
[ 422.    1.    2.    0.]
[ 472.    

In [1]:
for i in range(0,len(Subjects)):
    if Subjects[i].rid == 272:
        print(i)

NameError: name 'Subjects' is not defined

In [2]:
for s in Subjects:
    for j in s.jacobians:
        aux=np.asarray(j.dt)
        if aux < 0:
            print(s.rid)
            print(aux)

In [22]:
vars(Subjects[209].jacobians[15].target)

IndexError: list index out of range

In [23]:
Subjects[209].jacobians[2].label = 0
Subjects[209].jacobians[3].label = 0
Subjects[209].jacobians[4].label = 0
Subjects[209].jacobians[5].label = 0
Subjects[209].jacobians[6].label = 0
Subjects[209].jacobians[7].label = 0
Subjects[209].jacobians[8].label = 0
Subjects[209].jacobians[9].label = 0
Subjects[209].jacobians[10].label = 0
Subjects[209].jacobians[11].label = 0
Subjects[209].jacobians[12].label = 0
Subjects[209].jacobians[13].label = 0
Subjects[209].jacobians[14].label = 0

In [53]:
handle=open('./masterpickle.pickle', 'wb')
pickle.dump(Events, handle)
pickle.dump(subjdict, handle)
pickle.dump(subjects_rid, handle)
pickle.dump(Images, handle)
pickle.dump(Subjects, handle)
handle.close()